import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import MaxWidthWrapper from "@/components/max-width-wrapper";
import NavBar from "@/components/navigation-bar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} bg-zinc-100`}>
        <TRPCReactProvider>
          <NavBar />
          <MaxWidthWrapper className="py-10">{children}</MaxWidthWrapper>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
